# Generated by Django 4.2.4 on 2023-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_producer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='age',
            field=models.IntegerField(),
        ),
    ]
